### ISSUE TITLE
Default type for homepage should be added to the config

### ISSUE THREAD

**Issue by sabinebaer** [sulu-io/sulu-standard#455]
The parameter sulu.content.structure.default_type.homepage should be added to the config as it is used to determine the default template in sulu:webspaces:init (the parameter is set to overview by default and therefore an exception is thrown when overview.xml does not exist).

**Comment by wachterjohannes** [comment]
this should be able over the configuration:

```yml
sulu_core:
   content:
        structure:
            default_type:
                page: default
                snippet: default
                homepage: overview
```
