### ISSUE TITLE
SerializedName annotations are ignored

### ISSUE THREAD

**Issue by kriswillis** [sulu-io/sulu-standard#496]
When `IdenticalPropertyNamingStrategy` is enabled, it appears to override any `SerializedName` annotations defined on an API class.

Adding the following config appears to resolve this issue, as outlined at: https://github.com/schmittjoh/JMSSerializerBundle/pull/445

```yaml
parameters:
    jms_serializer.identical_property_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
    jms_serializer.identical_property_naming_strategy:
        class: %jms_serializer.identical_property_naming_strategy.class%
        public: false

    serialized_name_override_naming_strategy:
        class: %jms_serializer.serialized_name_annotation_strategy.class%
        public: false
        arguments:
            - @jms_serializer.identical_property_naming_strategy

    jms_serializer.naming_strategy:
        alias: serialized_name_override_naming_strategy
```
