### ISSUE TITLE
Conflict with FOS REST Bundle exception listener

### ISSUE THREAD

**Issue by sagikazarmark** [sulu-io/sulu-standard#640]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | develop

#### Actual Behavior

Currently FOS REST Bundle automatically registers it's exception listener:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/config/exception_listener.xml#L8

This "overrides" (or runs before) the core exception listener which means that the [exception controller override](https://github.com/sulu-io/sulu-standard/blob/develop/app/config/website/sulu.yml#L9) in sulu is not even taken into account.

As a result, the error templates defined for a webspace are not displayed correctly (for example with LexikMaintenanceBundle the custom 503 is not displayed, the core one is)

#### Expected Behavior

Desired error page is displayed.

#### Steps to Reproduce

Install [Lexik Maintenace Bundle](https://github.com/lexik/LexikMaintenanceBundle) and configure it:

``` yaml
lexik_maintenance:
    driver:
        class: Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver
        options:
            file_path: "%kernel.storage_dir%/var/cache/%sulu.context%/%kernel.environment%/maintenance_lock"
```

Then enable maintenance mode:

``` bash
$ app/console lexik:maintenance:lock --env prod
```

Note: prod mode is important, otherwise the debug page is displayed.

#### Possible Solutions

If the FOS REST Bundle is not required in the Website, it can be moved from abstract kernel to the admin. (Although it is not a real solution and is another argument for using two kernels, related sulu-io/sulu-standard#621)

For the moment, the template can be overriden in the app as the extension of the TwigBundle as well.

Ultimately it should be clarified if it is necessary in this context that the REST Bundle listener is used, and override it if not. It is possible by overriding the `fos_rest.exception_listener.controller` parameter or it can be disabled completely.
